version: '3.6'

services:
    piqueserver:
        image: ${P_IMAGE:-piqueserver/piqueserver}:${P_TAG:-dev}
        volumes:
            - config:/config
        ports:
            - "32887:32887"
            - "32886:32886"
            - "32885:32885"
            - "32887:32887/udp"

volumes:
    config:
