version: '3.6'

services:
    piqueserver:
        build:
            context: .
            dockerfile: ${P_DOCKERFILE:-Dockerfile}
        volumes:
            - ./piqueserver/config:/config
            - ./:/app/src/
